//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientMobileApp.Resources.Dictionary {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientMobileApp.Resources.Dictionary.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} Добро пожаловать !.
        /// </summary>
        internal static string _0001 {
            get {
                return ResourceManager.GetString("_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать !.
        /// </summary>
        internal static string _0002 {
            get {
                return ResourceManager.GetString("_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Забыли пароль.
        /// </summary>
        internal static string LogPbuttonForgot {
            get {
                return ResourceManager.GetString("LogPbuttonForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        internal static string LogPbuttonLogin {
            get {
                return ResourceManager.GetString("LogPbuttonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрироваться.
        /// </summary>
        internal static string LogPbuttonRegister {
            get {
                return ResourceManager.GetString("LogPbuttonRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пропустить.
        /// </summary>
        internal static string LogPbuttonSkip {
            get {
                return ResourceManager.GetString("LogPbuttonSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        internal static string LogPentryPassPlaceholder {
            get {
                return ResourceManager.GetString("LogPentryPassPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя пользователя.
        /// </summary>
        internal static string LogPentryUsernamePlaceholder {
            get {
                return ResourceManager.GetString("LogPentryUsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        internal static string LogPlabelPassword {
            get {
                return ResourceManager.GetString("LogPlabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать пароль.
        /// </summary>
        internal static string LogPlabelShowPassword {
            get {
                return ResourceManager.GetString("LogPlabelShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя.
        /// </summary>
        internal static string LogPlabelUsername {
            get {
                return ResourceManager.GetString("LogPlabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поля не должны быть пустыми.
        /// </summary>
        internal static string LogPloginAlertMessage {
            get {
                return ResourceManager.GetString("LogPloginAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одна из строк пустая.
        /// </summary>
        internal static string LogPloginAlertTitle {
            get {
                return ResourceManager.GetString("LogPloginAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        internal static string LogPpickerTitleLang {
            get {
                return ResourceManager.GetString("LogPpickerTitleLang", resourceCulture);
            }
        }
    }
}
